# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy_app', '0002_auto_20190329_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='join',
        ),
        migrations.AddField(
            model_name='trip',
            name='join_trip',
            field=models.ManyToManyField(related_name='join_other_trip', to='trip_buddy_app.User'),
        ),
    ]
